### PR TITLE
Fix the check for the kubernetes service.

### LINKED ISSUE #380: [Bug] CPEM fails to sync service when additional service is in default namespace
Hello,

When there is another service in `default` namespace, CPEM gets confused by it and does healthcheck (`doHealthCheck()`) using port specified by it instead of `default/kubernetes`.

In my instance I have additional service created by grafana-agent in default namespace:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: kubelet
  labels:
    app.kubernetes.io/managed-by: grafana-agent-operator
    app.kubernetes.io/name: kubelet
    k8s-app: kubelet
spec:
  type: ClusterIP
  ports:
  - targetPort: https-metrics
    port: 10250
    name: kubelet
  - targetPort: https-metrics
    port: 10255
    name: kubelet-read-only
  - targetPort: cadvisor
    port: 4194
    name: cadvisor
```

After this service was created CPEM log started to output this:
```sh
I0301 06:56:58.137339       1 eip_controlplane_reconciliation.go:206] handling update, service: default/kubelet
E0301 06:56:58.331549       1 eip_controlplane_reconciliation.go:135] failed to handle node health check: failed to assign the control plane endpoint: POST https://api.equinix.com/metal/v1/devices/0aeb3ae2-1c24-4718-9b39-a129e29e453e/ips: 500 Oh snap, something went wrong! We've logged the error and will take a look - please reach out to us if you continue having trouble. 
I0301 06:56:58.331594       1 eip_controlplane_reconciliation.go:125] handling update, node: iot-equinix-01-control-plane-c79zn
E0301 06:56:59.035057       1 eip_controlplane_reconciliation.go:209] failed to sync service from default/kubernetes to kube-system/cloud-provider-equinix-metal-kubernetes-external: failed to apply service kube-system/cloud-provider-equinix-metal-kubernetes-external: Service "cloud-provider-equinix-metal-kubernetes-external" is invalid: spec.ports[0]: Invalid value: 10250: may not expose port 10250 externally since it is used by kubelet
I0301 06:56:59.408680       1 eip_controlplane_reconciliation.go:521] doHealthCheck(): no control plane IP assignment found, trying to assign to an available controlplane node
I0301 06:56:59.412585       1 eip_controlplane_reconciliation.go:242] healthcheck node https://10.68.53.139:10250/healthz
I0301 06:56:59.414836       1 eip_controlplane_reconciliation.go:276] will not assign control plane endpoint to new device iot-equinix-01-control-plane-c79zn: returned http code 401
I0301 06:56:59.414843       1 eip_controlplane_reconciliation.go:242] healthcheck node https://147.28.128.229:10250/healthz
I0301 06:56:59.417049       1 eip_controlplane_reconciliation.go:276] will not assign control plane endpoint to new device iot-equinix-01-control-plane-c79zn: returned http code 401
I0301 06:56:59.417056       1 eip_controlplane_reconciliation.go:242] healthcheck node https://10.68.53.131:10250/healthz
I0301 06:56:59.420457       1 eip_controlplane_reconciliation.go:276] will not assign control plane endpoint to new device iot-equinix-01-control-plane-ws7kt: returned http code 401
I0301 06:56:59.420467       1 eip_controlplane_reconciliation.go:242] healthcheck node https://147.28.146.199:10250/healthz
```

As you can see for some reason it tries to apply service having port 10250 - `failed to apply service kube-system/cloud-provider-equinix-metal-kubernetes-external: Service "cloud-provider-equinix-metal-kubernetes-external" is invalid: spec.ports[0]: Invalid value: 10250: may not expose port 10250 externally since it is used by kubelet`.

Then additionally healthchecks started to use port `10250` and started to fail (correct port is 6443).

All this resulted into losing EIP assignment and losing access to control plane over load balancer created by CAPM. After service is deleted, CPEM starts to work correctly - so this is very easy to reproduce.

If you need any additional info, please let me know.

### PR DESCRIPTION
**Pull request by cprivitere**
Fixes #380

### CODE REVIEW

File: metal/eip_controlplane_reconciliation.go [hunk 1]
```diff
@@ -186,11 +186,12 @@ func newControlPlaneEndpointManager(k8sclient kubernetes.Interface, stop <-chan
 		cache.FilteringResourceEventHandler{
 			FilterFunc: func(obj interface{}) bool {
 				s, _ := obj.(*v1.Service)
-				if s.Namespace != metav1.NamespaceDefault && s.Name != "kubernetes" {
-					return false
+				// Filter only service default/kubernetes
+				if s.Namespace == metav1.NamespaceDefault && s.Name == "kubernetes" {
```
Comment (ctreatma) [inline metal/eip_controlplane_reconciliation.go:190]: Nit: this reduces to `return s.Namespace == metav1.NamespaceDefault && s.Name == "kubernetes"`

**Review by ctreatma — APPROVED** [review]
